/* This file is used to generate the tokens */

import { PinataSDK } from "pinata";

export const pinata = new PinataSDK({
    pinataJwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIzZDg3ZTQxYy1kNDhjLTQ2ZmUtODJjZS1lNThhOTI1ZmVjMjkiLCJlbWFpbCI6ImhhcnNoaXRoYXNhcmF2YW5hbjI1QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiI2YmUzYmIzZjAzYWNiMGJjYzZjZSIsInNjb3BlZEtleVNlY3JldCI6IjBhODU0ZjYwNWM0OTUwNWEwMzVmOTA0YzFlNjczZjA2NTczYjgyMmFlMThiNmI0ZjNjNzZjZjVkMWEyYmU2NTQiLCJleHAiOjE3NTU0ODc3MDJ9.GfxH7ZGD-EWbRbzXi-bHuboxMugvdIidxdBqONrjPsM",
    pinataGateway: "maroon-quick-weasel-161.mypinata.cloud"
})